### ISSUE TITLE
Recursive delete support

### ISSUE THREAD

**Issue by SerialVelocity** [palantir/hadoop-crypto#93]
Sometime between 2.0.0-rc7 and 2.3.2 recursive deletes started throwing an exception about them being unsupported.

It would be nice if this was supported so that whole folders of encrypted data can be deleted easily. See internal backup solution PR 720.

**Comment by jpfourny** [comment]
+1. We can't use this crypto library with Spark (and many other Hadoop based tools) without recursive delete support. Hadoop job cleanup uses recursive delete on temp directories.

**Comment by ellisjoe** [comment]
@sandorw do you recall why we didn't want to support recursive deletes? the exception was added here: https://github.com/palantir/hadoop-crypto/pull/47/files

**Comment by sandorw** [comment]
IIRC, the reason was that, while it's well supported for file based key storage, it's harder to implement for `InMemoryKeyStorageStrategy` without changing the current simple implementation. Since it wasn't clear we needed it at the time, we opted out of the extra complexity.

**Comment by ellisjoe** [comment]
Fixed by https://github.com/palantir/hadoop-crypto/pull/111

**Comment by ashrayjain** [comment]
@ellisjoe We are still getting this from `EncryptedFileSystem`. Specifically, this line:

https://github.com/palantir/hadoop-crypto/blob/develop/hadoop-crypto/src/main/java/com/palantir/crypto2/hadoop/EncryptedFileSystem.java#L147

**Comment by ellisjoe** [comment]
At the moment that is expected behavior. You should use the StandaloneEncryptedFileSystem if you're using the FileKeyStorageStrategy and need recursive deletes.

**Comment by ashrayjain** [comment]
Cool, that's what we ended up doing. Thanks!
